### PR TITLE
added star and spacted icons

### PR DESCRIPTION
**Pull request by YASH4801**
added icons for star and spactate

### CODE REVIEW

**Comment by rudrabarad** [comment]
Hello @YASH4801 

Since your pull request doesn't have a significant contribution, so I'll need to add the **invalid** label to it.
So, I'll request you to create an octocat and then create a **Pull Request**

I'll wait today until 10 PM. If there will not be any significant contributions then I'll need to mark in **INVALID**

Thank you

**Comment by YASH4801** [comment]
now i created a pull request for a significant contribution, please review
it.

**Comment by rudrabarad** [comment]
Thank you 😄 
Spread the word to your peers and colleagues! 

Apart from Hacktoberfest's T-Shirt and goodies, If you Create 3 Pull Request in [CLub Gamma's Projects](https://github.com/clubgamma) you could win a T-Shirt and Goodies from [Club Gamma](https://clubgamma.github.io/hacktoberfest/) as well.

**Comment by YASH4801** [comment]
thanks for the info.

**Pull request merged**
